### ISSUE TITLE
conflux.web3j.RpcException: RPC error: code = -32015, message = Estimation isn't accurate: transaction is reverted.【放弃吧，换js-sdk】

### ISSUE THREAD

**Issue by 1991wangliang** [Conflux-Chain/java-conflux-sdk#31]
```

conflux.web3j.RpcException: RPC error: code = -32015, message = Estimation isn't accurate: transaction is reverted. Innermost error is at CFXTEST:TYPE.CONTRACT:ACDDH6V0XPXCXYAZB6ECU9D971PNA0NCFYWHW3B956: Vm reverted. ., data = "0x434658544553543a545950452e434f4e54524143543a4143444448365630585058435859415a42364543553944393731504e41304e43465957485733423935363a20566d2072657665727465642e20"

	at conflux.web3j.Request.sendAndGet(Request.java:69)
	at conflux.web3j.Request.sendAndGet(Request.java:62)
	at conflux.web3j.Request.sendAndGet(Request.java:58)
	at conflux.web3j.Account$Option.applyDefault(Account.java:288)
	at conflux.web3j.Account$Option.buildTx(Account.java:300)
	at conflux.web3j.Account$Option.access$000(Account.java:178)
	at conflux.web3j.Account.buildRawTransaction(Account.java:127)
	at conflux.web3j.Account.callWithData(Account.java:174)
	at conflux.web3j.Account.call(Account.java:166)
	at com.codingapi.confluxcontract.ContractTest.update(ContractTest.java:60)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.junit.platform.commons.util.ReflectionUtils.invokeMethod(ReflectionUtils.java:725)
	at org.junit.jupiter.engine.execution.MethodInvocation.proceed(MethodInvocation.java:60)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$ValidatingInvocation.proceed(InvocationInterceptorChain.java:131)
	at org.junit.jupiter.engine.extension.TimeoutExtension.intercept(TimeoutExtension.java:149)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestableMethod(TimeoutExtension.java:140)
	at org.junit.jupiter.engine.extension.TimeoutExtension.interceptTestMethod(TimeoutExtension.java:84)
	at org.junit.jupiter.engine.execution.ExecutableInvoker$ReflectiveInterceptorCall.lambda$ofVoidMethod$0(ExecutableInvoker.java:115)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.lambda$invoke$0(ExecutableInvoker.java:105)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain$InterceptedInvocation.proceed(InvocationInterceptorChain.java:106)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.proceed(InvocationInterceptorChain.java:64)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.chainAndInvoke(InvocationInterceptorChain.java:45)
	at org.junit.jupiter.engine.execution.InvocationInterceptorChain.invoke(InvocationInterceptorChain.java:37)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:104)
	at org.junit.jupiter.engine.execution.ExecutableInvoker.invoke(ExecutableInvoker.java:98)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.lambda$invokeTestMethod$7(TestMethodTestDescriptor.java:214)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.invokeTestMethod(TestMethodTestDescriptor.java:210)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:135)
	at org.junit.jupiter.engine.descriptor.TestMethodTestDescriptor.execute(TestMethodTestDescriptor.java:66)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:151)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at java.util.ArrayList.forEach(ArrayList.java:1259)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.invokeAll(SameThreadHierarchicalTestExecutorService.java:41)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$6(NodeTestTask.java:155)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$8(NodeTestTask.java:141)
	at org.junit.platform.engine.support.hierarchical.Node.around(Node.java:137)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.lambda$executeRecursively$9(NodeTestTask.java:139)
	at org.junit.platform.engine.support.hierarchical.ThrowableCollector.execute(ThrowableCollector.java:73)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.executeRecursively(NodeTestTask.java:138)
	at org.junit.platform.engine.support.hierarchical.NodeTestTask.execute(NodeTestTask.java:95)
	at org.junit.platform.engine.support.hierarchical.SameThreadHierarchicalTestExecutorService.submit(SameThreadHierarchicalTestExecutorService.java:35)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestExecutor.execute(HierarchicalTestExecutor.java:57)
	at org.junit.platform.engine.support.hierarchical.HierarchicalTestEngine.execute(HierarchicalTestEngine.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:107)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:88)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.lambda$execute$0(EngineExecutionOrchestrator.java:54)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.withInterceptedStreams(EngineExecutionOrchestrator.java:67)
	at org.junit.platform.launcher.core.EngineExecutionOrchestrator.execute(EngineExecutionOrchestrator.java:52)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:114)
	at org.junit.platform.launcher.core.DefaultLauncher.execute(DefaultLauncher.java:86)
	at org.junit.platform.launcher.core.DefaultLauncherSession$DelegatingLauncher.execute(DefaultLauncherSession.java:86)
	at org.junit.platform.launcher.core.SessionPerRequestLauncher.execute(SessionPerRequestLauncher.java:53)
	at com.intellij.junit5.JUnit5IdeaTestRunner.startRunnerWithArgs(JUnit5IdeaTestRunner.java:71)
	at com.intellij.rt.junit.IdeaTestRunner$Repeater.startRunnerWithArgs(IdeaTestRunner.java:33)
	at com.intellij.rt.junit.JUnitStarter.prepareStreamsAndStart(JUnitStarter.java:220)
	at com.intellij.rt.junit.JUnitStarter.main(JUnitStarter.java:53)
```

code:
```
 String privateKey = "0x...";
//        int netId = 1;
        Address contractAddress = new Address("cfxtest:acddh6v0xpxcxyazb6ecu9d971pna0ncfywhw3b956");
        Address userAddress = new Address("cfxtest:aat6twwp0z9dpntk0exgu43f5g6rhrxa2ap8k64z4j");

//        BigInteger amount = new BigInteger("1");

        Cfx cfx = Cfx.create("https://test.confluxrpc.com", 3, 1000);
//        ContractCall contract = new ContractCall(cfx, contractAddress);
        // create account, then call contract's method
        Account account = Account.create(cfx, privateKey);
        Account.Option opt = new Account.Option();
        // build transaction option info: nonce, gas, gasPrice and etc
        opt.withChainId(userAddress.getNetworkId());
//        opt.withGasLimit(1000000000000L);
//        opt.withGasPrice(new BigInteger("10000000"));
//        opt.withValue(new BigInteger("3"));

//        opt.withValue(new BigInteger());


        String txHash = account.call(
                opt,
                contractAddress,
                "safeTransferFrom",
                account.getAddress().getABIAddress(),
                userAddress.getABIAddress(),
                new Uint256(1),
                new Uint256(1),
                Bytes32.DEFAULT
        );

        System.out.println("tx hash: " + txHash);
```

**Comment by 1991wangliang** [comment]
logs:
```
12:53:59.029 [main] DEBUG org.web3j.protocol.http.HttpService - --> POST https://test.confluxrpc.com/
12:53:59.032 [main] DEBUG org.web3j.protocol.http.HttpService - Content-Type: application/json; charset=utf-8
12:53:59.032 [main] DEBUG org.web3j.protocol.http.HttpService - Content-Length: 61
12:53:59.032 [main] DEBUG org.web3j.protocol.http.HttpService - 
12:53:59.033 [main] DEBUG org.web3j.protocol.http.HttpService - {"jsonrpc":"2.0","method":"cfx_getStatus","params":[],"id":0}
12:53:59.033 [main] DEBUG org.web3j.protocol.http.HttpService - --> END POST (61-byte body)
12:53:59.369 [main] DEBUG org.web3j.protocol.http.HttpService - <-- 200 https://test.confluxrpc.com/ (336ms)
12:53:59.369 [main] DEBUG org.web3j.protocol.http.HttpService - date: Fri, 01 Apr 2022 04:53:59 GMT
12:53:59.369 [main] DEBUG org.web3j.protocol.http.HttpService - content-type: application/json
12:53:59.369 [main] DEBUG org.web3j.protocol.http.HttpService - vary: Origin
12:53:59.369 [main] DEBUG org.web3j.protocol.http.HttpService - referrer-policy: origin-when-cross-origin
12:53:59.369 [main] DEBUG org.web3j.protocol.http.HttpService - x-content-type-options: nosniff
12:53:59.369 [main] DEBUG org.web3j.protocol.http.HttpService - x-xss-protection: 1; mode=block
12:53:59.369 [main] DEBUG org.web3j.protocol.http.HttpService - x-frame-options: SAMEORIGIN
12:53:59.370 [main] DEBUG org.web3j.protocol.http.HttpService - 
12:53:59.370 [main] DEBUG org.web3j.protocol.http.HttpService - {"jsonrpc":"2.0","id":0,"result":{"bestHash":"0xc70e357503c77fb840d8c446418cf746772619c52335ef05dc622345e5a81ab7","chainId":"0x1","ethereumSpaceChainId":"0x47","networkId":"0x1","epochNumber":"0x4298264","blockNumber":"0x544b1a1","pendingTxNumber":"0x1fb","latestCheckpoint":"0x427d7c0","latestConfirmed":"0x4298225","latestState":"0x4298260","latestFinalized":"0x4298070"}}

12:53:59.370 [main] DEBUG org.web3j.protocol.http.HttpService - <-- END HTTP (375-byte body)
12:53:59.724 [main] DEBUG org.web3j.protocol.http.HttpService - --> POST https://test.confluxrpc.com/
12:53:59.724 [main] DEBUG org.web3j.protocol.http.HttpService - Content-Type: application/json; charset=utf-8
12:53:59.724 [main] DEBUG org.web3j.protocol.http.HttpService - Content-Length: 116
12:53:59.724 [main] DEBUG org.web3j.protocol.http.HttpService - 
12:53:59.724 [main] DEBUG org.web3j.protocol.http.HttpService - {"jsonrpc":"2.0","method":"txpool_nextNonce","params":["cfxtest:aathtsjfep11dbe59csj34b985n1ag0hjep28d85rd"],"id":1}
12:53:59.724 [main] DEBUG org.web3j.protocol.http.HttpService - --> END POST (116-byte body)
12:53:59.785 [main] DEBUG org.web3j.protocol.http.HttpService - <-- 200 https://test.confluxrpc.com/ (60ms)
12:53:59.785 [main] DEBUG org.web3j.protocol.http.HttpService - date: Fri, 01 Apr 2022 04:54:00 GMT
12:53:59.785 [main] DEBUG org.web3j.protocol.http.HttpService - content-type: application/json
12:53:59.785 [main] DEBUG org.web3j.protocol.http.HttpService - vary: Origin
12:53:59.785 [main] DEBUG org.web3j.protocol.http.HttpService - referrer-policy: origin-when-cross-origin
12:53:59.785 [main] DEBUG org.web3j.protocol.http.HttpService - x-content-type-options: nosniff
12:53:59.785 [main] DEBUG org.web3j.protocol.http.HttpService - x-xss-protection: 1; mode=block
12:53:59.785 [main] DEBUG org.web3j.protocol.http.HttpService - x-frame-options: SAMEORIGIN
12:53:59.785 [main] DEBUG org.web3j.protocol.http.HttpService - 
12:53:59.785 [main] DEBUG org.web3j.protocol.http.HttpService - {"jsonrpc":"2.0","id":1,"result":"0x184"}

12:53:59.785 [main] DEBUG org.web3j.protocol.http.HttpService - <-- END HTTP (42-byte body)
12:53:59.787 [main] DEBUG org.web3j.protocol.http.HttpService - --> POST https://test.confluxrpc.com/
12:53:59.787 [main] DEBUG org.web3j.protocol.http.HttpService - Content-Type: application/json; charset=utf-8
12:53:59.787 [main] DEBUG org.web3j.protocol.http.HttpService - Content-Length: 63
12:53:59.787 [main] DEBUG org.web3j.protocol.http.HttpService - 
12:53:59.787 [main] DEBUG org.web3j.protocol.http.HttpService - {"jsonrpc":"2.0","method":"cfx_epochNumber","params":[],"id":2}
12:53:59.787 [main] DEBUG org.web3j.protocol.http.HttpService - --> END POST (63-byte body)
12:53:59.827 [main] DEBUG org.web3j.protocol.http.HttpService - <-- 200 https://test.confluxrpc.com/ (39ms)
12:53:59.827 [main] DEBUG org.web3j.protocol.http.HttpService - date: Fri, 01 Apr 2022 04:54:00 GMT
12:53:59.827 [main] DEBUG org.web3j.protocol.http.HttpService - content-type: application/json
12:53:59.827 [main] DEBUG org.web3j.protocol.http.HttpService - vary: Origin
12:53:59.827 [main] DEBUG org.web3j.protocol.http.HttpService - referrer-policy: origin-when-cross-origin
12:53:59.828 [main] DEBUG org.web3j.protocol.http.HttpService - x-content-type-options: nosniff
12:53:59.828 [main] DEBUG org.web3j.protocol.http.HttpService - x-xss-protection: 1; mode=block
12:53:59.828 [main] DEBUG org.web3j.protocol.http.HttpService - x-frame-options: SAMEORIGIN
12:53:59.828 [main] DEBUG org.web3j.protocol.http.HttpService - 
12:53:59.828 [main] DEBUG org.web3j.protocol.http.HttpService - {"jsonrpc":"2.0","id":2,"result":"0x4298265"}

12:53:59.828 [main] DEBUG org.web3j.protocol.http.HttpService - <-- END HTTP (46-byte body)
12:53:59.831 [main] DEBUG org.web3j.protocol.http.HttpService - --> POST https://test.confluxrpc.com/
12:53:59.831 [main] DEBUG org.web3j.protocol.http.HttpService - Content-Type: application/json; charset=utf-8
12:53:59.831 [main] DEBUG org.web3j.protocol.http.HttpService - Content-Length: 609
12:53:59.831 [main] DEBUG org.web3j.protocol.http.HttpService - 
12:53:59.831 [main] DEBUG org.web3j.protocol.http.HttpService - {"jsonrpc":"2.0","method":"cfx_estimateGasAndCollateral","params":[{"from":"cfxtest:aathtsjfep11dbe59csj34b985n1ag0hjep28d85rd","to":"cfxtest:acddh6v0xpxcxyazb6ecu9d971pna0ncfywhw3b956","gasPrice":null,"gas":null,"value":"0x0","data":"0xe4ea88360000000000000000000000001e77b905232f71849bf89c8ce83ff6d7701ac7410000000000000000000000001fc7ca4cb57e362de9b126686b25d9b8d3b660c0000000000000000000000000000000000000000000000000000000000000000100000000000000000000000000000000000000000000000000000000000000010000000000000000000000000000000000000000000000000000000000000000","nonce":null,"storageLimit":null}],"id":3}
12:53:59.831 [main] DEBUG org.web3j.protocol.http.HttpService - --> END POST (609-byte body)
12:53:59.870 [main] DEBUG org.web3j.protocol.http.HttpService - <-- 200 https://test.confluxrpc.com/ (38ms)
12:53:59.870 [main] DEBUG org.web3j.protocol.http.HttpService - date: Fri, 01 Apr 2022 04:54:00 GMT
12:53:59.870 [main] DEBUG org.web3j.protocol.http.HttpService - content-type: application/json
12:53:59.870 [main] DEBUG org.web3j.protocol.http.HttpService - vary: Origin
12:53:59.870 [main] DEBUG org.web3j.protocol.http.HttpService - referrer-policy: origin-when-cross-origin
12:53:59.870 [main] DEBUG org.web3j.protocol.http.HttpService - x-content-type-options: nosniff
12:53:59.870 [main] DEBUG org.web3j.protocol.http.HttpService - x-xss-protection: 1; mode=block
12:53:59.870 [main] DEBUG org.web3j.protocol.http.HttpService - x-frame-options: SAMEORIGIN
12:53:59.870 [main] DEBUG org.web3j.protocol.http.HttpService - 
12:53:59.870 [main] DEBUG org.web3j.protocol.http.HttpService - {"jsonrpc":"2.0","id":3,"error":{"code":-32015,"message":"Estimation isn't accurate: transaction is reverted. Innermost error is at CFXTEST:TYPE.CONTRACT:ACDDH6V0XPXCXYAZB6ECU9D971PNA0NCFYWHW3B956: Vm reverted. .","data":"0x434658544553543a545950452e434f4e54524143543a4143444448365630585058435859415a42364543553944393731504e41304e43465957485733423935363a20566d2072657665727465642e20"}}

12:53:59.870 [main] DEBUG org.web3j.protocol.http.HttpService - <-- END HTTP (386-byte body)
```
